In [2]:
import numpy as np
import pandas as pd

#### 1. Load the data

In [3]:
## Read the “housing.csv” file from the folder into the program
houseData = pd.read_excel('1553768847_housing.xlsx')

In [4]:
houseData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
longitude             20640 non-null float64
latitude              20640 non-null float64
housing_median_age    20640 non-null int64
total_rooms           20640 non-null int64
total_bedrooms        20433 non-null float64
population            20640 non-null int64
households            20640 non-null int64
median_income         20640 non-null float64
ocean_proximity       20640 non-null object
median_house_value    20640 non-null int64
dtypes: float64(4), int64(5), object(1)
memory usage: 1.6+ MB

In [9]:
## Print first few rows of this data.
houseData.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity,median_house_value
0,-122.23,37.88,41,880,129.0,322,126,8.3252,NEAR BAY,452600
1,-122.22,37.86,21,7099,1106.0,2401,1138,8.3014,NEAR BAY,358500
2,-122.24,37.85,52,1467,190.0,496,177,7.2574,NEAR BAY,352100
3,-122.25,37.85,52,1274,235.0,558,219,5.6431,NEAR BAY,341300
4,-122.25,37.85,52,1627,280.0,565,259,3.8462,NEAR BAY,342200

In [4]:
houseData.total_bedrooms.value_counts(dropna=False)

NaN       207
280.0      55
331.0      51
345.0      50
393.0      49
343.0      49
394.0      48
328.0      48
348.0      48
272.0      47
309.0      47
295.0      46
314.0      46
322.0      46
399.0      46
317.0      46
284.0      45
388.0      45
290.0      45
291.0      45
346.0      45
287.0      45
340.0      45
313.0      45
269.0      44
460.0      44
365.0      44
294.0      44
361.0      44
312.0      44
         ...
2814.0      1
6445.0      1
2141.0      1
2460.0      1
3479.0      1
1758.0      1
1127.0      1
2010.0      1
1571.0      1
3224.0      1
1494.0      1
1052.0      1
2574.0      1
1570.0      1
1437.0      1
2118.0      1
3336.0      1
2289.0      1
1736.0      1
940.0       1
980.0       1
1215.0      1
2009.0      1
3864.0      1
1288.0      1
1691.0      1
2205.0      1
1448.0      1
1887.0      1
2546.0      1
Name: total_bedrooms, Length: 1924, dtype: int64

In [5]:
## Extract input (X) and output (Y) data from the dataset.
X = houseData.iloc[:,:9]
Y = houseData.iloc[:,[9]]

#### 2. Handle missing values :

In [6]:
## Fill the missing values with the mean of the respective column.
houseData.total_bedrooms.fillna(houseData.total_bedrooms.mean(), inplace=True)

#### 3. Encode categorical data

In [7]:

features = houseData.iloc[:,[0,1,2,3,4,5,6,7,8]].values
label = houseData.iloc[:,[9]].values

In [8]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [9]:
## Convert categorical column in the dataset to numerical data.

oceanProxLabel = LabelEncoder()
features[:,8] = oceanProxLabel.fit_transform(features[:,8])

In [10]:
oceanProxLabel.classes_

array(['<1H OCEAN', 'INLAND', 'ISLAND', 'NEAR BAY', 'NEAR OCEAN'],
      dtype=object)

In [11]:
oceanProxOHE = OneHotEncoder(categorical_features=[8])

In [12]:
features = oceanProxOHE .fit_transform(features).toarray()

C:\Users\u275000\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\u275000\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)

In [13]:
pd.DataFrame(features)

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,0.0,0.0,0.0,1.0,0.0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252
1,0.0,0.0,0.0,1.0,0.0,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014
2,0.0,0.0,0.0,1.0,0.0,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574
3,0.0,0.0,0.0,1.0,0.0,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431
4,0.0,0.0,0.0,1.0,0.0,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462
5,0.0,0.0,0.0,1.0,0.0,-122.25,37.85,52.0,919.0,213.0,413.0,193.0,4.0368
6,0.0,0.0,0.0,1.0,0.0,-122.25,37.84,52.0,2535.0,489.0,1094.0,514.0,3.6591
7,0.0,0.0,0.0,1.0,0.0,-122.25,37.84,52.0,3104.0,687.0,1157.0,647.0,3.1200
8,0.0,0.0,0.0,1.0,0.0,-122.26,37.84,42.0,2555.0,665.0,1206.0,595.0,2.0804
9,0.0,0.0,0.0,1.0,0.0,-122.25,37.84,52.0,3549.0,707.0,1551.0,714.0,3.6912
10,0.0,0.0,0.0,1.0,0.0,-122.26,37.85,52.0,2202.0,434.0,910.0,402.0,3.2031
11,0.0,0.0,0.0,1.0,0.0,-122.26,37.85,52.0,3503.0,752.0,1504.0,734.0,3.2705
12,0.0,0.0,0.0,1.0,0.0,-122.26,37.85,52.0,2491.0,474.0,1098.0,468.0,3.0750
13,0.0,0.0,0.0,1.0,0.0,-122.26,37.84,52.0,696.0,191.0,345.0,174.0,2.6736
14,0.0,0.0,0.0,1.0,0.0,-122.26,37.85,52.0,2643.0,626.0,1212.0,620.0,1.9167
15,0.0,0.0,0.0,1.0,0.0,-122.26,37.85,50.0,1120.0,283.0,697.0,264.0,2.1250
16,0.0,0.0,0.0,1.0,0.0,-122.27,37.85,52.0,1966.0,347.0,793.0,331.0,2.7750
17,0.0,0.0,0.0,1.0,0.0,-122.27,37.85,52.0,1228.0,293.0,648.0,303.0,2.1202
18,0.0,0.0,0.0,1.0,0.0,-122.26,37.84,50.0,2239.0,455.0,990.0,419.0,1.9911
19,0.0,0.0,0.0,1.0,0.0,-122.27,37.84,52.0,1503.0,298.0,690.0,275.0,2.6033
20,0.0,0.0,0.0,1.0,0.0,-122.27,37.85,40.0,751.0,184.0,409.0,166.0,1.3578
21,0.0,0.0,0.0,1.0,0.0,-122.27,37.85,42.0,1639.0,367.0,929.0,366.0,1.7135
22,0.0,0.0,0.0,1.0,0.0,-122.27,37.84,52.0,2436.0,541.0,1015.0,478.0,1.7250
23,0.0,0.0,0.0,1.0,0.0,-122.27,37.84,52.0,1688.0,337.0,853.0,325.0,2.1806
24,0.0,0.0,0.0,1.0,0.0,-122.27,37.84,52.0,2224.0,437.0,1006.0,422.0,2.6000
25,0.0,0.0,0.0,1.0,0.0,-122.28,37.85,41.0,535.0,123.0,317.0,119.0,2.4038
26,0.0,0.0,0.0,1.0,0.0,-122.28,37.85,49.0,1130.0,244.0,607.0,239.0,2.4597
27,0.0,0.0,0.0,1.0,0.0,-122.28,37.85,52.0,1898.0,421.0,1102.0,397.0,1.8080
28,0.0,0.0,0.0,1.0,0.0,-122.28,37.84,50.0,2082.0,492.0,1131.0,473.0,1.6424
29,0.0,0.0,0.0,1.0,0.0,-122.28,37.84,52.0,729.0,160.0,395.0,155.0,1.6875
...,...,...,...,...,...,...,...,...,...,...,...,...,...
20610,0.0,1.0,0.0,0.0,0.0,-121.56,39.10,28.0,2130.0,484.0,1195.0,439.0,1.3631
20611,0.0,1.0,0.0,0.0,0.0,-121.55,39.10,27.0,1783.0,441.0,1163.0,409.0,1.2857
20612,0.0,1.0,0.0,0.0,0.0,-121.56,39.08,26.0,1377.0,289.0,761.0,267.0,1.4934
20613,0.0,1.0,0.0,0.0,0.0,-121.55,39.09,31.0,1728.0,365.0,1167.0,384.0,1.4958
20614,0.0,1.0,0.0,0.0,0.0,-121.54,39.08,26.0,2276.0,460.0,1455.0,474.0,2.4695
20615,0.0,1.0,0.0,0.0,0.0,-121.54,39.08,23.0,1076.0,216.0,724.0,197.0,2.3598
20616,0.0,1.0,0.0,0.0,0.0,-121.53,39.08,15.0,1810.0,441.0,1157.0,375.0,2.0469
20617,0.0,1.0,0.0,0.0,0.0,-121.53,39.06,20.0,561.0,109.0,308.0,114.0,3.3021
20618,0.0,1.0,0.0,0.0,0.0,-121.55,39.06,25.0,1332.0,247.0,726.0,226.0,2.2500
20619,0.0,1.0,0.0,0.0,0.0,-121.56,39.01,22.0,1891.0,340.0,1023.0,296.0,2.7303
20620,0.0,1.0,0.0,0.0,0.0,-121.48,39.05,40.0,198.0,41.0,151.0,48.0,4.5625
20621,0.0,1.0,0.0,0.0,0.0,-121.47,39.01,37.0,1244.0,247.0,484.0,157.0,2.3661
20622,0.0,1.0,0.0,0.0,0.0,-121.44,39.00,20.0,755.0,147.0,457.0,157.0,2.4167
20623,0.0,1.0,0.0,0.0,0.0,-121.37,39.03,32.0,1158.0,244.0,598.0,227.0,2.8235
20624,0.0,1.0,0.0,0.0,0.0,-121.41,39.04,16.0,1698.0,300.0,731.0,291.0,3.0739
20625,0.0,1.0,0.0,0.0,0.0,-121.52,39.12,37.0,102.0,17.0,29.0,14.0,4.1250
20626,0.0,1.0,0.0,0.0,0.0,-121.43,39.18,36.0,1124.0,184.0,504.0,171.0,2.1667
20627,0.0,1.0,0.0,0.0,0.0,-121.32,39.13,5.0,358.0,65.0,169.0,59.0,3.0000
20628,0.0,1.0,0.0,0.0,0.0,-121.48,39.10,19.0,2043.0,421.0,1018.0,390.0,2.5952
20629,0.0,1.0,0.0,0.0,0.0,-121.39,39.12,28.0,10035.0,1856.0,6912.0,1818.0,2.0943
20630,0.0,1.0,0.0,0.0,0.0,-121.32,39.29,11.0,2640.0,505.0,1257.0,445.0,3.5673
20631,0.0,1.0,0.0,0.0,0.0,-121.40,39.33,15.0,2655.0,493.0,1200.0,432.0,3.5179
20632,0.0,1.0,0.0,0.0,0.0,-121.45,39.26,15.0,2319.0,416.0,1047.0,385.0,3.1250
20633,0.0,1.0,0.0,0.0,0.0,-121.53,39.19,27.0,2080.0,412.0,1082.0,382.0,2.5495
20634,0.0,1.0,0.0,0.0,0.0,-121.56,39.27,28.0,2332.0,395.0,1041.0,344.0,3.7125
20635,0.0,1.0,0.0,0.0,0.0,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603
20636,0.0,1.0,0.0,0.0,0.0,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568
20637,0.0,1.0,0.0,0.0,0.0,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000
20638,0.0,1.0,0.0,0.0,0.0,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672
20639,0.0,1.0,0.0,0.0,0.0,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886

#### 4. Split the dataset :

In [59]:
## Split the data into 80% training dataset and 20% test dataset.

In [14]:
## Cross Validation Score

In [15]:
from sklearn.linear_model import LinearRegression
modelCrossVal = LinearRegression()

In [16]:
from sklearn.model_selection import cross_val_score
cvResult = cross_val_score(modelCrossVal,
                            features,
                          label,
                          cv=5)

In [18]:
cvResult.mean()

0.5596714644247107

In [19]:
# We have assigned ourself a benchmark stating our model must have accuracy >= 55.97%

In [20]:
## KFold Cross Validation

In [21]:
from sklearn.model_selection import KFold
kfold_Housedata = KFold(n_splits=5,
                       shuffle=True,
                       random_state=1)

In [30]:
i = 0
for train_kfold, test_kfold in kfold_Housedata.split(features):
    i = i + 1
    X_train_kfold, X_test_kfold = features[train_kfold], features[test_kfold]
    y_train_kfold, y_test_kfold = label[train_kfold], label[test_kfold]
    modelCrossVal.fit(X_train_kfold, y_train_kfold)

    if i == 4:
        X_train_Kfinal,X_test_Kfinal,y_train_Kfinal,y_test_Kfinal = features[train_kfold],features[test_kfold],label[train_kfold],label[test_kfold]
    else:
        print('Testing Score: {} Training Score: {} for Sample Split : {} '
          .format(modelCrossVal.score(X_test_kfold,y_test_kfold),modelCrossVal.score(X_train_kfold,y_train_kfold),i))

Testing Score: 0.6375631694383567 Training Score: 0.6471768442653696 for Sample Split : 1
Testing Score: 0.6569483771576241 Training Score: 0.6423243920531152 for Sample Split : 2
Testing Score: 0.6252507989546705 Training Score: 0.6497542031605482 for Sample Split : 3
Testing Score: 0.6391488010642277 Training Score: 0.6468859860349323 for Sample Split : 5

### 5. Standardize data :

In [91]:
## Standardize training and test datasets.
from sklearn.preprocessing import MinMaxScaler
scaleData = MinMaxScaler(feature_range=(0,1))
features_scaled = scaleData.fit_transform(features)

In [92]:
pd.DataFrame(features_scaled).head()

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,0.0,0.0,0.0,1.0,0.0,0.211155,0.567481,0.784314,0.022331,0.019863,0.008941,0.020556,0.539668
1,0.0,0.0,0.0,1.0,0.0,0.212151,0.565356,0.392157,0.180503,0.171477,0.067210,0.186976,0.538027
2,0.0,0.0,0.0,1.0,0.0,0.210159,0.564293,1.000000,0.037260,0.029330,0.013818,0.028943,0.466028
3,0.0,0.0,0.0,1.0,0.0,0.209163,0.564293,1.000000,0.032352,0.036313,0.015555,0.035849,0.354699
4,0.0,0.0,0.0,1.0,0.0,0.209163,0.564293,1.000000,0.041330,0.043296,0.015752,0.042427,0.230776

In [35]:
## Feature Engineering using ANOVA
from sklearn.feature_selection import SelectPercentile
from sklearn.feature_selection import f_regression # -------> For Regression
#from sklearn.feature_selection import f_classif ------->classification Algo

selectFeatures = SelectPercentile(percentile=50, score_func=f_regression) #for classification: score_func=f_classif

selectFeatures.fit(features,label)

finalFeaturesANOVA = selectFeatures.transform(features)
print("Total features {}, After Anova {}".format(features.shape,finalFeaturesANOVA.shape))
print(selectFeatures.get_support())
# '<1H OCEAN', 'INLAND', 'ISLAND', 'NEAR BAY', 'NEAR OCEAN', longitude, latitude, housing_median_age, total_rooms,
## total_bedrooms, population, households, median_income

Total features (20640, 13), After Anova (20640, 6)
[ True  True False  True  True False  True False False False False False
  True]

C:\Users\u275000\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

#### 6. Perform Linear Regression :

In [40]:
## Perform Linear Regression on training data.

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

for i in range(1,20641):
    from sklearn.model_selection import train_test_split
    X_train,X_test,y_train,y_test = train_test_split(features,
                                                label,
                                                test_size=0.2,
                                                random_state=i)
    model_linear = LinearRegression()
    model_linear.fit(X_train,y_train)
    
    train_score = model_linear.score(X_train,y_train)
    test_score = model_linear.score(X_test,y_test)
    
    if (test_score > train_score) and (test_score > 0.675) :
        print("Testing: {} Training: {} RandomState: {}".format(test_score,train_score,i))

Testing: 0.6777317560953721 Training: 0.6373514208619753 RandomState: 719
Testing: 0.6873007735236054 Training: 0.6348224925701187 RandomState: 928
Testing: 0.6776589458467651 Training: 0.6369056569171951 RandomState: 987
Testing: 0.6777101650797324 Training: 0.6370301600504048 RandomState: 1225
Testing: 0.6811064112810449 Training: 0.6362310620844351 RandomState: 1973
Testing: 0.679348088244752 Training: 0.6366935501343439 RandomState: 2467
Testing: 0.6785920628918554 Training: 0.6367738385507198 RandomState: 3088
Testing: 0.6763591825706947 Training: 0.637167756812502 RandomState: 4921
Testing: 0.6758975570022648 Training: 0.6374093644626257 RandomState: 5066
Testing: 0.6778887776431005 Training: 0.6375614138960156 RandomState: 6097
Testing: 0.6759775588297703 Training: 0.6373102926282077 RandomState: 7058
Testing: 0.6750861973923107 Training: 0.6377858877475064 RandomState: 7158
Testing: 0.679293319658914 Training: 0.636736457010275 RandomState: 7600
Testing: 0.6767852224819689 Training: 0.6375551033969533 RandomState: 7851
Testing: 0.679684094252262 Training: 0.6360614306587967 RandomState: 8010
Testing: 0.6774701391235449 Training: 0.6370112912729928 RandomState: 8048
Testing: 0.675433254936391 Training: 0.6378684292260778 RandomState: 8565
Testing: 0.676141939144143 Training: 0.6374112645104533 RandomState: 8996
Testing: 0.67621778368833 Training: 0.6378562363726188 RandomState: 11301
Testing: 0.6771881223792943 Training: 0.6375093108988563 RandomState: 15602
Testing: 0.6765674064588609 Training: 0.6373114406410576 RandomState: 15674
Testing: 0.6852927875336404 Training: 0.6356392859352953 RandomState: 17304
Testing: 0.6753239853896236 Training: 0.6376760917088335 RandomState: 17583
Testing: 0.6765030091761695 Training: 0.637813536708449 RandomState: 18584
Testing: 0.6750526636931955 Training: 0.6378677080601101 RandomState: 19652
Testing: 0.6756250294790728 Training: 0.6379007733021953 RandomState: 20425

In [41]:
X_train,X_test,y_train,y_test = train_test_split(features,
                                                label,
                                                test_size=0.2,
                                                random_state=928)

In [42]:
print(model_linear.score(X_train,y_train))
print(model_linear.score(X_test,y_test))

0.6346752662419911
0.6877173268695581

In [47]:
## Predict output for test dataset using the fitted model.
y_pred = model_linear.predict(X_test)

In [48]:
## Print root mean squared error (RMSE) from Linear Regression.
from sklearn import metrics

print(metrics.mean_absolute_error(y_test, y_pred))
print(metrics.mean_squared_error(y_test, y_pred))
print(np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

48148.82534017358
4196628944.0734353
64781.39350209623

#### 7. Perform Decision Tree Regression :

In [68]:
## Perform Decision Tree Regression on training data.
from sklearn.tree import DecisionTreeRegressor
model_decision = DecisionTreeRegressor(max_depth=5)
model_decision.fit(X_train,y_train)

DecisionTreeRegressor(criterion='mse', max_depth=5, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=None, splitter='best')

In [69]:
model_decision.score(X_train, y_train)

0.6322819319744304

In [70]:
model_decision.score(X_test, y_test)

0.651982735057933

In [86]:
## Predict output for test dataset using the fitted model.
y_pred = model_decision.predict(X_test)

In [87]:
## Print root mean squared error (RMSE) from Decision Tree.
from sklearn import metrics

print(metrics.mean_absolute_error(y_test, y_pred))
print(metrics.mean_squared_error(y_test, y_pred))
print(np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

48771.115400117764
4676850343.480611
68387.50136889497

#### 8. Perform Random Forest Regression :

In [83]:
## Perform Random Forest Regression on training data.
from sklearn.ensemble import RandomForestRegressor
model_RF = RandomForestRegressor(max_depth=5, n_estimators=10)
model_RF.fit(X_train,y_train)

C:\Users\u275000\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=5,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [84]:
model_RF.score(X_train, y_train)

0.6541009654733875

In [85]:
model_RF.score(X_test, y_test)

0.6800915024956031

In [89]:
## Predict output for test dataset using the fitted model.
y_pred = model_RF.predict(X_test)

In [90]:
## Print root mean squared error (RMSE) from Random Tree.
from sklearn import metrics

print(metrics.mean_absolute_error(y_test, y_pred))
print(metrics.mean_squared_error(y_test, y_pred))
print(np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

47075.954692197614
4299109030.366254
65567.59131130451